sudo: true
os: trusty
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core

- sfdx force:auth:jwt:grant --clientid 3MVG9d8..z.hDcPK0eaClfjO_Ue_NgCsQbOU7a1j3wkEoZQJKH4Dnwqge_pBbqBR3q69eVN_6Onqbgt7MCka0 --username herman.castano.dx@gmail.com --jwtkeyfile assets/server.key --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait 7
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg

- sfdx force:package:install -i 04t50000000cSq7AAE -u ciorg -w 10
- sfdx force:package:install -i 04t80000001AWUFAA4 -u ciorg -w 10
- sfdx force:package:install -i 04t80000000gZTWAA2 -u ciorg -w 10
- sfdx force:package:install -i 04t80000000tqAcAAI -u ciorg -w 10
- sfdx force:package:install -i 04t80000000lTMlAAM -u ciorg -w 10
- sfdx force:package:install -i 04t80000000y8kRAAQ -u ciorg -w 10
- sfdx force:package:install -i 04ti0000000GSu9AAG -u ciorg -w 10
- sfdx force:package:install -i 04t1Y0000011SYRQA2 -u ciorg -w 10

- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
